### ISSUE TITLE
Nested Exposure attributes are flatten in documents

### ISSUE THREAD

**Issue by calfzhou** [intridea/grape-entity#112]
the [Nested Exposure](https://github.com/intridea/grape-entity#nested-exposure) generates incorrect documentation, all nested fields are flatten
```ruby
expose :name
expose :contact_info do
  expose :phone
  expose :email
end
```

it should generate (document)
```yaml
name: ...
contact_info:
  phone: ...
  email: ...
```

but now it generates
```yaml
name: ...
phone: ...
email: ...
```
